### ISSUE TITLE
Comparison with binarycor.pco IDL program

### ISSUE THREAD

**Issue by SergeiDBykov** [piexpiex/X-ray-pulsars-Pulse-Profile#3]
Hi!
I have a question: Have you compared your code with the results of the original IDL program?

I cannot try it out because don't have IDL licence.

**Comment by piexpiex** [comment]
Hi,

The code was translated from these IDL codes http://astro.uni-tuebingen.de/software/idl/aitlib/astro/, I tested the code with examples and later the pulses profiles of differents sources have resulted correct.

In my program the true anomaly is calculated with the orbit parameters (and the times by iterations) and in your case is a initial parameter, maybe here is the mistake.

regards.
________________________________
De: Sergei Bykov <notifications@github.com>
Enviado: domingo, 8 de marzo de 2020 10:21
Para: piexpiex/X-ray-pulsars-Pulse-Profile <X-ray-pulsars-Pulse-Profile@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [piexpiex/X-ray-pulsars-Pulse-Profile] Comparison with binarycor.pco IDL program (#3)


Hi!
I have a question: Have you compared your code with the results of the original IDL program?

I cannot try it out because don't have IDL licence.

The problem is that I cannot reproduce the output of your program by Solving Kepler Equation in my way (i.e. just calculating the Z coordinate of objecct as z(t)=rsini(t)*sin(omega_d+v), (v - true anomaly)

**Comment by SergeiDBykov** [comment]
> Hi, The code was translated from these IDL codes http://astro.uni-tuebingen.de/software/idl/aitlib/astro/, I tested the code with examples and later the pulses profiles of differents sources have resulted correct. In my program the true anomaly is calculated with the orbit parameters (and the times by iterations) and in your case is a initial parameter, maybe here is the mistake. regards.


Thanks!
